export const mentors = [
  {
    name: "Mohamed Abdelaziz",
    title: "Software Engineer",
    image: "/src/assets/mentor-1.webp",
    rate: "4.5",
    exp: "4",
    track: "Frontend",
  },
  {
    name: "Menna Ahmed",
    title: "Product Designer",
    image: "/src/assets/mentor-2.webp",
    rate: "4.5",
    exp: "4",
    track: "UI/UX",
  },
  {
    name: "Mahmoud Radwan",
    title: "Software Engineer",
    image: "/src/assets/mentor-3.webp",
    rate: "4.5",
    exp: "5",
    track: "Backend",
  },
  {
    name: "Yomna Hegazy",
    title: "Product Designer",
    image: "/src/assets/mentor-4.webp",
    rate: "4.5",
    exp: "3",
    track: "UI/UX",
  },
  {
    name: "Aya Etman",
    title: "Software Engineer",
    image: "/src/assets/mentor-5.webp",
    rate: "4.5",
    exp: "7",
    track: "Frontend",
  },
  {
    name: "Ahmed Hassan",
    title: "Product Designer",
    image: "/src/assets/mentor-6.webp",
    rate: "4.5",
    exp: "4",
    track: "UI/UX",
  },
  {
    name: "Ahmed Nagy",
    title: "Software Engineer",
    image: "/src/assets/mentor-7.webp",
    rate: "4.5",
    exp: "6",
    track: "Backend",
  },
  {
    name: "Abdo Kamar",
    title: "Product Designer",
    image: "/src/assets/mentor-8.webp",
    rate: "4.5",
    exp: "3",
    track: "UI/UX",
  },
];
